import os
from datetime import timedelta
from pathlib import Path
BASE_DIR=Path(__file__).resolve().parent.parent
SECRET_KEY=os.getenv('DJANGO_SECRET_KEY','dev-only-change-me-please-use-a-real-secret-key');DEBUG=os.getenv('DJANGO_DEBUG','true').lower()=='true'
if not DEBUG and SECRET_KEY=='dev-only-change-me-please-use-a-real-secret-key': raise RuntimeError('DJANGO_SECRET_KEY must be configured outside development.')
ALLOWED_HOSTS=[h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS','localhost,127.0.0.1').split(',') if h.strip()]
INSTALLED_APPS=['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','rest_framework','apps.core','apps.accounts','apps.homes','apps.devices','apps.iot','apps.resources','apps.automation','apps.security','apps.reports','apps.recommendations','apps.simulator','apps.dashboard']
MIDDLEWARE=['django.middleware.security.SecurityMiddleware','django.middleware.gzip.GZipMiddleware','django.contrib.sessions.middleware.SessionMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware']
ROOT_URLCONF='ecohome.urls';TEMPLATES=[{'BACKEND':'django.template.backends.django.DjangoTemplates','DIRS':[],'APP_DIRS':True,'OPTIONS':{'context_processors':['django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages']}}];WSGI_APPLICATION='ecohome.wsgi.application';ASGI_APPLICATION='ecohome.asgi.application'
if os.getenv('POSTGRES_HOST'): DATABASES={'default':{'ENGINE':'django.db.backends.postgresql','NAME':os.getenv('POSTGRES_DB','ecohome'),'USER':os.getenv('POSTGRES_USER','ecohome'),'PASSWORD':os.getenv('POSTGRES_PASSWORD',''),'HOST':os.getenv('POSTGRES_HOST','localhost'),'PORT':os.getenv('POSTGRES_PORT','5432'),'CONN_MAX_AGE':60,'CONN_HEALTH_CHECKS':True}}
else:DATABASES={'default':{'ENGINE':'django.db.backends.sqlite3','NAME':BASE_DIR/'db.sqlite3'}}
AUTH_PASSWORD_VALIDATORS=[{'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},{'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator'},{'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator'},{'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE='es-do';TIME_ZONE='America/Santo_Domingo';USE_I18N=True;USE_TZ=True;STATIC_URL='static/';STATIC_ROOT=BASE_DIR/'staticfiles';DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
REST_FRAMEWORK={'DEFAULT_AUTHENTICATION_CLASSES':['rest_framework_simplejwt.authentication.JWTAuthentication'],'DEFAULT_PERMISSION_CLASSES':['rest_framework.permissions.IsAuthenticated'],'DEFAULT_RENDERER_CLASSES':['rest_framework.renderers.JSONRenderer'],'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination','PAGE_SIZE':25,'DEFAULT_THROTTLE_CLASSES':['rest_framework.throttling.UserRateThrottle','rest_framework.throttling.AnonRateThrottle'],'DEFAULT_THROTTLE_RATES':{'user':'120/min','anon':'30/min'}}
SIMPLE_JWT={'ACCESS_TOKEN_LIFETIME':timedelta(minutes=30),'REFRESH_TOKEN_LIFETIME':timedelta(days=7),'ROTATE_REFRESH_TOKENS':True,'BLACKLIST_AFTER_ROTATION':False}
SECURE_CONTENT_TYPE_NOSNIFF=True;X_FRAME_OPTIONS='DENY';SECURE_REFERRER_POLICY='same-origin';CSRF_COOKIE_HTTPONLY=True;CSRF_COOKIE_SECURE=not DEBUG;SESSION_COOKIE_SECURE=not DEBUG;SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO','https');SECURE_SSL_REDIRECT=(not DEBUG and os.getenv('DJANGO_SECURE_SSL_REDIRECT','false').lower()=='true');SECURE_HSTS_SECONDS=0 if DEBUG else int(os.getenv('DJANGO_HSTS_SECONDS','3600'));SECURE_HSTS_INCLUDE_SUBDOMAINS=not DEBUG;SECURE_HSTS_PRELOAD=False
LOGGING={'version':1,'disable_existing_loggers':False,'handlers':{'console':{'class':'logging.StreamHandler'}},'root':{'handlers':['console'],'level':os.getenv('DJANGO_LOG_LEVEL','INFO')}}
